apiVersion: v1
kind: Service
metadata:
  name: hotel-reservation-service
spec:
  selector:
    app: hotel-reservation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
